// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// hpaBinary
List hpaBinary(Rcpp::Formula formula, DataFrame data, int K, double z_mean_fixed, double z_sd_fixed, double z_constant_fixed, bool is_z_coef_first_fixed, bool is_x0_probit, bool is_sequence, NumericVector x0);
RcppExport SEXP _hpa_hpaBinary(SEXP formulaSEXP, SEXP dataSEXP, SEXP KSEXP, SEXP z_mean_fixedSEXP, SEXP z_sd_fixedSEXP, SEXP z_constant_fixedSEXP, SEXP is_z_coef_first_fixedSEXP, SEXP is_x0_probitSEXP, SEXP is_sequenceSEXP, SEXP x0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Formula >::type formula(formulaSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type z_mean_fixed(z_mean_fixedSEXP);
    Rcpp::traits::input_parameter< double >::type z_sd_fixed(z_sd_fixedSEXP);
    Rcpp::traits::input_parameter< double >::type z_constant_fixed(z_constant_fixedSEXP);
    Rcpp::traits::input_parameter< bool >::type is_z_coef_first_fixed(is_z_coef_first_fixedSEXP);
    Rcpp::traits::input_parameter< bool >::type is_x0_probit(is_x0_probitSEXP);
    Rcpp::traits::input_parameter< bool >::type is_sequence(is_sequenceSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x0(x0SEXP);
    rcpp_result_gen = Rcpp::wrap(hpaBinary(formula, data, K, z_mean_fixed, z_sd_fixed, z_constant_fixed, is_z_coef_first_fixed, is_x0_probit, is_sequence, x0));
    return rcpp_result_gen;
END_RCPP
}
// predict_Binary
NumericVector predict_Binary(List model, DataFrame newdata, bool is_prob);
RcppExport SEXP _hpa_predict_Binary(SEXP modelSEXP, SEXP newdataSEXP, SEXP is_probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type newdata(newdataSEXP);
    Rcpp::traits::input_parameter< bool >::type is_prob(is_probSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_Binary(model, newdata, is_prob));
    return rcpp_result_gen;
END_RCPP
}
// summary_Binary
List summary_Binary(List model);
RcppExport SEXP _hpa_summary_Binary(SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(summary_Binary(model));
    return rcpp_result_gen;
END_RCPP
}
// print_summary_Binary
void print_summary_Binary(List model);
RcppExport SEXP _hpa_print_summary_Binary(SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    print_summary_Binary(model);
    return R_NilValue;
END_RCPP
}
// plot_Binary
void plot_Binary(List model);
RcppExport SEXP _hpa_plot_Binary(SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    plot_Binary(model);
    return R_NilValue;
END_RCPP
}
// AIC_Binary
double AIC_Binary(List model);
RcppExport SEXP _hpa_AIC_Binary(SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(AIC_Binary(model));
    return rcpp_result_gen;
END_RCPP
}
// logLik_Binary
double logLik_Binary(List model);
RcppExport SEXP _hpa_logLik_Binary(SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(logLik_Binary(model));
    return rcpp_result_gen;
END_RCPP
}
// hpaML
List hpaML(NumericMatrix x, NumericVector pol_degrees, NumericVector tr_left, NumericVector tr_right, LogicalVector given_ind, LogicalVector omit_ind, NumericVector x0);
RcppExport SEXP _hpa_hpaML(SEXP xSEXP, SEXP pol_degreesSEXP, SEXP tr_leftSEXP, SEXP tr_rightSEXP, SEXP given_indSEXP, SEXP omit_indSEXP, SEXP x0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pol_degrees(pol_degreesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tr_left(tr_leftSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tr_right(tr_rightSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type given_ind(given_indSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type omit_ind(omit_indSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x0(x0SEXP);
    rcpp_result_gen = Rcpp::wrap(hpaML(x, pol_degrees, tr_left, tr_right, given_ind, omit_ind, x0));
    return rcpp_result_gen;
END_RCPP
}
// predict_ML
NumericVector predict_ML(List model, NumericMatrix newdata);
RcppExport SEXP _hpa_predict_ML(SEXP modelSEXP, SEXP newdataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type newdata(newdataSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_ML(model, newdata));
    return rcpp_result_gen;
END_RCPP
}
// summary_ML
List summary_ML(List model);
RcppExport SEXP _hpa_summary_ML(SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(summary_ML(model));
    return rcpp_result_gen;
END_RCPP
}
// print_summary_ML
void print_summary_ML(List model);
RcppExport SEXP _hpa_print_summary_ML(SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    print_summary_ML(model);
    return R_NilValue;
END_RCPP
}
// AIC_ML
double AIC_ML(List model);
RcppExport SEXP _hpa_AIC_ML(SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(AIC_ML(model));
    return rcpp_result_gen;
END_RCPP
}
// logLik_ML
double logLik_ML(List model);
RcppExport SEXP _hpa_logLik_ML(SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(logLik_ML(model));
    return rcpp_result_gen;
END_RCPP
}
// dhpa
NumericVector dhpa(NumericMatrix x, NumericVector pol_coefficients, NumericVector pol_degrees, LogicalVector given_ind, LogicalVector omit_ind, NumericVector mean, NumericVector sd);
RcppExport SEXP _hpa_dhpa(SEXP xSEXP, SEXP pol_coefficientsSEXP, SEXP pol_degreesSEXP, SEXP given_indSEXP, SEXP omit_indSEXP, SEXP meanSEXP, SEXP sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pol_coefficients(pol_coefficientsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pol_degrees(pol_degreesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type given_ind(given_indSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type omit_ind(omit_indSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sd(sdSEXP);
    rcpp_result_gen = Rcpp::wrap(dhpa(x, pol_coefficients, pol_degrees, given_ind, omit_ind, mean, sd));
    return rcpp_result_gen;
END_RCPP
}
// phpa
NumericVector phpa(NumericMatrix x, NumericVector pol_coefficients, NumericVector pol_degrees, LogicalVector given_ind, LogicalVector omit_ind, NumericVector mean, NumericVector sd);
RcppExport SEXP _hpa_phpa(SEXP xSEXP, SEXP pol_coefficientsSEXP, SEXP pol_degreesSEXP, SEXP given_indSEXP, SEXP omit_indSEXP, SEXP meanSEXP, SEXP sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pol_coefficients(pol_coefficientsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pol_degrees(pol_degreesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type given_ind(given_indSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type omit_ind(omit_indSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sd(sdSEXP);
    rcpp_result_gen = Rcpp::wrap(phpa(x, pol_coefficients, pol_degrees, given_ind, omit_ind, mean, sd));
    return rcpp_result_gen;
END_RCPP
}
// ihpa
NumericVector ihpa(NumericMatrix x_lower, NumericMatrix x_upper, NumericVector pol_coefficients, NumericVector pol_degrees, LogicalVector given_ind, LogicalVector omit_ind, NumericVector mean, NumericVector sd);
RcppExport SEXP _hpa_ihpa(SEXP x_lowerSEXP, SEXP x_upperSEXP, SEXP pol_coefficientsSEXP, SEXP pol_degreesSEXP, SEXP given_indSEXP, SEXP omit_indSEXP, SEXP meanSEXP, SEXP sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x_lower(x_lowerSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x_upper(x_upperSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pol_coefficients(pol_coefficientsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pol_degrees(pol_degreesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type given_ind(given_indSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type omit_ind(omit_indSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sd(sdSEXP);
    rcpp_result_gen = Rcpp::wrap(ihpa(x_lower, x_upper, pol_coefficients, pol_degrees, given_ind, omit_ind, mean, sd));
    return rcpp_result_gen;
END_RCPP
}
// ehpa
NumericVector ehpa(NumericMatrix x, NumericVector pol_coefficients, NumericVector pol_degrees, LogicalVector given_ind, LogicalVector omit_ind, NumericVector mean, NumericVector sd, NumericVector expectation_powers);
RcppExport SEXP _hpa_ehpa(SEXP xSEXP, SEXP pol_coefficientsSEXP, SEXP pol_degreesSEXP, SEXP given_indSEXP, SEXP omit_indSEXP, SEXP meanSEXP, SEXP sdSEXP, SEXP expectation_powersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pol_coefficients(pol_coefficientsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pol_degrees(pol_degreesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type given_ind(given_indSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type omit_ind(omit_indSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type expectation_powers(expectation_powersSEXP);
    rcpp_result_gen = Rcpp::wrap(ehpa(x, pol_coefficients, pol_degrees, given_ind, omit_ind, mean, sd, expectation_powers));
    return rcpp_result_gen;
END_RCPP
}
// etrhpa
NumericVector etrhpa(NumericMatrix tr_left, NumericMatrix tr_right, NumericVector pol_coefficients, NumericVector pol_degrees, NumericVector mean, NumericVector sd, NumericVector expectation_powers);
RcppExport SEXP _hpa_etrhpa(SEXP tr_leftSEXP, SEXP tr_rightSEXP, SEXP pol_coefficientsSEXP, SEXP pol_degreesSEXP, SEXP meanSEXP, SEXP sdSEXP, SEXP expectation_powersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tr_left(tr_leftSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tr_right(tr_rightSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pol_coefficients(pol_coefficientsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pol_degrees(pol_degreesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type expectation_powers(expectation_powersSEXP);
    rcpp_result_gen = Rcpp::wrap(etrhpa(tr_left, tr_right, pol_coefficients, pol_degrees, mean, sd, expectation_powers));
    return rcpp_result_gen;
END_RCPP
}
// dtrhpa
NumericVector dtrhpa(NumericMatrix x, NumericMatrix tr_left, NumericMatrix tr_right, NumericVector pol_coefficients, NumericVector pol_degrees, LogicalVector given_ind, LogicalVector omit_ind, NumericVector mean, NumericVector sd);
RcppExport SEXP _hpa_dtrhpa(SEXP xSEXP, SEXP tr_leftSEXP, SEXP tr_rightSEXP, SEXP pol_coefficientsSEXP, SEXP pol_degreesSEXP, SEXP given_indSEXP, SEXP omit_indSEXP, SEXP meanSEXP, SEXP sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tr_left(tr_leftSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tr_right(tr_rightSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pol_coefficients(pol_coefficientsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pol_degrees(pol_degreesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type given_ind(given_indSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type omit_ind(omit_indSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sd(sdSEXP);
    rcpp_result_gen = Rcpp::wrap(dtrhpa(x, tr_left, tr_right, pol_coefficients, pol_degrees, given_ind, omit_ind, mean, sd));
    return rcpp_result_gen;
END_RCPP
}
// itrhpa
NumericVector itrhpa(NumericMatrix x_lower, NumericMatrix x_upper, NumericMatrix tr_left, NumericMatrix tr_right, NumericVector pol_coefficients, NumericVector pol_degrees, LogicalVector given_ind, LogicalVector omit_ind, NumericVector mean, NumericVector sd);
RcppExport SEXP _hpa_itrhpa(SEXP x_lowerSEXP, SEXP x_upperSEXP, SEXP tr_leftSEXP, SEXP tr_rightSEXP, SEXP pol_coefficientsSEXP, SEXP pol_degreesSEXP, SEXP given_indSEXP, SEXP omit_indSEXP, SEXP meanSEXP, SEXP sdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x_lower(x_lowerSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x_upper(x_upperSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tr_left(tr_leftSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tr_right(tr_rightSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pol_coefficients(pol_coefficientsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pol_degrees(pol_degreesSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type given_ind(given_indSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type omit_ind(omit_indSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sd(sdSEXP);
    rcpp_result_gen = Rcpp::wrap(itrhpa(x_lower, x_upper, tr_left, tr_right, pol_coefficients, pol_degrees, given_ind, omit_ind, mean, sd));
    return rcpp_result_gen;
END_RCPP
}
// hpaSelection
Rcpp::List hpaSelection(Rcpp::Formula selection, Rcpp::Formula outcome, DataFrame data, int z_K, int y_K, int pol_elements, bool is_Newey, NumericVector x0);
RcppExport SEXP _hpa_hpaSelection(SEXP selectionSEXP, SEXP outcomeSEXP, SEXP dataSEXP, SEXP z_KSEXP, SEXP y_KSEXP, SEXP pol_elementsSEXP, SEXP is_NeweySEXP, SEXP x0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Formula >::type selection(selectionSEXP);
    Rcpp::traits::input_parameter< Rcpp::Formula >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type z_K(z_KSEXP);
    Rcpp::traits::input_parameter< int >::type y_K(y_KSEXP);
    Rcpp::traits::input_parameter< int >::type pol_elements(pol_elementsSEXP);
    Rcpp::traits::input_parameter< bool >::type is_Newey(is_NeweySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x0(x0SEXP);
    rcpp_result_gen = Rcpp::wrap(hpaSelection(selection, outcome, data, z_K, y_K, pol_elements, is_Newey, x0));
    return rcpp_result_gen;
END_RCPP
}
// predict_Selection
List predict_Selection(List model, DataFrame newdata, std::string method, bool is_cond, bool is_outcome);
RcppExport SEXP _hpa_predict_Selection(SEXP modelSEXP, SEXP newdataSEXP, SEXP methodSEXP, SEXP is_condSEXP, SEXP is_outcomeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type newdata(newdataSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type is_cond(is_condSEXP);
    Rcpp::traits::input_parameter< bool >::type is_outcome(is_outcomeSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_Selection(model, newdata, method, is_cond, is_outcome));
    return rcpp_result_gen;
END_RCPP
}
// summary_Selection
List summary_Selection(List model);
RcppExport SEXP _hpa_summary_Selection(SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(summary_Selection(model));
    return rcpp_result_gen;
END_RCPP
}
// print_summary_Selection
void print_summary_Selection(List model);
RcppExport SEXP _hpa_print_summary_Selection(SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    print_summary_Selection(model);
    return R_NilValue;
END_RCPP
}
// plot_Selection
List plot_Selection(List model, bool is_outcome);
RcppExport SEXP _hpa_plot_Selection(SEXP modelSEXP, SEXP is_outcomeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< bool >::type is_outcome(is_outcomeSEXP);
    rcpp_result_gen = Rcpp::wrap(plot_Selection(model, is_outcome));
    return rcpp_result_gen;
END_RCPP
}
// AIC_Selection
double AIC_Selection(List model);
RcppExport SEXP _hpa_AIC_Selection(SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(AIC_Selection(model));
    return rcpp_result_gen;
END_RCPP
}
// logLik_Selection
double logLik_Selection(List model);
RcppExport SEXP _hpa_logLik_Selection(SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(logLik_Selection(model));
    return rcpp_result_gen;
END_RCPP
}
// normalMoment
NumericMatrix normalMoment(int k, double mean, double sd, bool return_all_moments, bool is_validation);
RcppExport SEXP _hpa_normalMoment(SEXP kSEXP, SEXP meanSEXP, SEXP sdSEXP, SEXP return_all_momentsSEXP, SEXP is_validationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< bool >::type return_all_moments(return_all_momentsSEXP);
    Rcpp::traits::input_parameter< bool >::type is_validation(is_validationSEXP);
    rcpp_result_gen = Rcpp::wrap(normalMoment(k, mean, sd, return_all_moments, is_validation));
    return rcpp_result_gen;
END_RCPP
}
// truncatedNormalMoment
NumericMatrix truncatedNormalMoment(int k, NumericVector x_lower, NumericVector x_upper, double mean, double sd, NumericVector pdf_lower, NumericVector cdf_lower, NumericVector pdf_upper, NumericVector cdf_upper, NumericVector cdf_difference, bool return_all_moments, bool is_validation);
RcppExport SEXP _hpa_truncatedNormalMoment(SEXP kSEXP, SEXP x_lowerSEXP, SEXP x_upperSEXP, SEXP meanSEXP, SEXP sdSEXP, SEXP pdf_lowerSEXP, SEXP cdf_lowerSEXP, SEXP pdf_upperSEXP, SEXP cdf_upperSEXP, SEXP cdf_differenceSEXP, SEXP return_all_momentsSEXP, SEXP is_validationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_lower(x_lowerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_upper(x_upperSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pdf_lower(pdf_lowerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cdf_lower(cdf_lowerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pdf_upper(pdf_upperSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cdf_upper(cdf_upperSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cdf_difference(cdf_differenceSEXP);
    Rcpp::traits::input_parameter< bool >::type return_all_moments(return_all_momentsSEXP);
    Rcpp::traits::input_parameter< bool >::type is_validation(is_validationSEXP);
    rcpp_result_gen = Rcpp::wrap(truncatedNormalMoment(k, x_lower, x_upper, mean, sd, pdf_lower, cdf_lower, pdf_upper, cdf_upper, cdf_difference, return_all_moments, is_validation));
    return rcpp_result_gen;
END_RCPP
}
// polynomialIndex
NumericMatrix polynomialIndex(NumericVector pol_degrees);
RcppExport SEXP _hpa_polynomialIndex(SEXP pol_degreesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pol_degrees(pol_degreesSEXP);
    rcpp_result_gen = Rcpp::wrap(polynomialIndex(pol_degrees));
    return rcpp_result_gen;
END_RCPP
}
// printPolynomial
Rcpp::String printPolynomial(NumericVector pol_degrees, NumericVector pol_coefficients);
RcppExport SEXP _hpa_printPolynomial(SEXP pol_degreesSEXP, SEXP pol_coefficientsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pol_degrees(pol_degreesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pol_coefficients(pol_coefficientsSEXP);
    rcpp_result_gen = Rcpp::wrap(printPolynomial(pol_degrees, pol_coefficients));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hpa_hpaBinary", (DL_FUNC) &_hpa_hpaBinary, 10},
    {"_hpa_predict_Binary", (DL_FUNC) &_hpa_predict_Binary, 3},
    {"_hpa_summary_Binary", (DL_FUNC) &_hpa_summary_Binary, 1},
    {"_hpa_print_summary_Binary", (DL_FUNC) &_hpa_print_summary_Binary, 1},
    {"_hpa_plot_Binary", (DL_FUNC) &_hpa_plot_Binary, 1},
    {"_hpa_AIC_Binary", (DL_FUNC) &_hpa_AIC_Binary, 1},
    {"_hpa_logLik_Binary", (DL_FUNC) &_hpa_logLik_Binary, 1},
    {"_hpa_hpaML", (DL_FUNC) &_hpa_hpaML, 7},
    {"_hpa_predict_ML", (DL_FUNC) &_hpa_predict_ML, 2},
    {"_hpa_summary_ML", (DL_FUNC) &_hpa_summary_ML, 1},
    {"_hpa_print_summary_ML", (DL_FUNC) &_hpa_print_summary_ML, 1},
    {"_hpa_AIC_ML", (DL_FUNC) &_hpa_AIC_ML, 1},
    {"_hpa_logLik_ML", (DL_FUNC) &_hpa_logLik_ML, 1},
    {"_hpa_dhpa", (DL_FUNC) &_hpa_dhpa, 7},
    {"_hpa_phpa", (DL_FUNC) &_hpa_phpa, 7},
    {"_hpa_ihpa", (DL_FUNC) &_hpa_ihpa, 8},
    {"_hpa_ehpa", (DL_FUNC) &_hpa_ehpa, 8},
    {"_hpa_etrhpa", (DL_FUNC) &_hpa_etrhpa, 7},
    {"_hpa_dtrhpa", (DL_FUNC) &_hpa_dtrhpa, 9},
    {"_hpa_itrhpa", (DL_FUNC) &_hpa_itrhpa, 10},
    {"_hpa_hpaSelection", (DL_FUNC) &_hpa_hpaSelection, 8},
    {"_hpa_predict_Selection", (DL_FUNC) &_hpa_predict_Selection, 5},
    {"_hpa_summary_Selection", (DL_FUNC) &_hpa_summary_Selection, 1},
    {"_hpa_print_summary_Selection", (DL_FUNC) &_hpa_print_summary_Selection, 1},
    {"_hpa_plot_Selection", (DL_FUNC) &_hpa_plot_Selection, 2},
    {"_hpa_AIC_Selection", (DL_FUNC) &_hpa_AIC_Selection, 1},
    {"_hpa_logLik_Selection", (DL_FUNC) &_hpa_logLik_Selection, 1},
    {"_hpa_normalMoment", (DL_FUNC) &_hpa_normalMoment, 5},
    {"_hpa_truncatedNormalMoment", (DL_FUNC) &_hpa_truncatedNormalMoment, 12},
    {"_hpa_polynomialIndex", (DL_FUNC) &_hpa_polynomialIndex, 1},
    {"_hpa_printPolynomial", (DL_FUNC) &_hpa_printPolynomial, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_hpa(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
